import = ["~/.config/alacritty/colors.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 10
y = 10
